---
- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: yes
  become: yes

- name: Ensure PostgreSQL is started and enabled
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Create PostgreSQL user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB,LOGIN
  become: yes
  become_user: postgres

- name: Create PostgreSQL database
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    encoding: UTF-8
  become: yes
  become_user: postgres

- name: Configure PostgreSQL to accept remote connections
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
    mode: '0640'
    owner: postgres
    group: postgres
  become: yes
  notify: restart postgresql

- name: Configure PostgreSQL to listen on all addresses
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    line: "listen_addresses = '*'"
    regexp: "^#?listen_addresses"
    state: present
  become: yes
  notify: restart postgresql